### PR TITLE
feat: add algolia based search support

### LINKED ISSUE #57: Add search bar
Docusaurus supports searching through the documentation thanks to Agolia https://docusaurus.io/docs/search. Let's add that to our site :)

We already did talk about this in the initial PR but search wasn't a blocking point for the initial release because the previous esdoc search only searched through the API reference (which is still there)

### PR DESCRIPTION
**Pull request by ephys**
This PR adds support for a search bar, courtesy of Algolia Docsearch :)

image

closes #57

### CODE REVIEW

**Review by WikiRik — APPROVED** [review]
It seems to work fine, but I still find it strange that the API key is exposed. But if that's according to the docusaurus guide it should be fine

**Comment by evanrittenhouse** [comment]
@WikiRik agreed, are we opposed to just putting it in an environment variable or something? Why are we exposing it?

**Comment by ephys** [comment]
Can't, it's static, it's added to the front-end

**Comment by WikiRik** [comment]
Yup, @ephys mentioned it where I asked her personally as well that it's supposed to end in the frontend JS. I still find it weird but if the key is limited enough it should be find

**Comment by fzn0x** [comment]
Maybe they have some functionality to limit the API Key on some domains only I guess?

**Review by fzn0x — APPROVED** [review]

**Comment by ephys** [comment]
Yes this API key is only able to search & nothing more

Screenshot_20220925-100507

**Comment by fzn0x** [comment]
Can we merge this? This is very helpful PR.

**Pull request merged**
