### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by mjunix**
Added missing `await`s.

Also removed some calls to `toJSON()`. `findAll()` returns an [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) so we can't call `toJSON()` on it, an alternative could be to call `JSON.stringify()` like `console.log(JSON.stringify((await ...), null, 2));` but I personally thought it made the code look too cluttered.

### CODE REVIEW

**Comment by WikiRik** [comment]
We have some breaking changes in v7 for associations, for which the documentation will be updated here; https://github.com/sequelize/website/pull/197

It might be better to point this PR towards that branch instead of to the `main` branch (if these changes still make sense in that PR)

**Review by sdepold — APPROVED** [review]

**Comment by sdepold** [comment]
Ah good point @WikiRik

**Review by ephys — APPROVED** [review]

**Review by sdepold — APPROVED** [review]

**Comment by sdepold** [comment]
@WikiRik Shall we merge this?

**Comment by WikiRik** [comment]
If @ephys approves then I think we should be fine

**Comment by ephys** [comment]
I do agree with your comment that since we need to rewrite the association docs, this will eventually be lost. We should replicate the changes in the v6 folder

**Comment by WikiRik** [comment]
Agree, @mjunix can you copy the changes to https://github.com/sequelize/website/blob/main/versioned_docs/version-6.x.x/core-concepts/assocs.md as well?

**Pull request closed without merging**
