### PR TITLE
docs(model): Added paranoid option for Model.BelongsToMany.through 

### PR DESCRIPTION
**Pull request by ajatdarojat45**
Because in Model.BelongsToMany.through documentation there is no paranoid option so i adding it in documentation.

### CODE REVIEW

**Comment by ephys** [comment]
Thank you for the PR but unfortunately Sequelize 5 has been EOL since last January, and we don't accept any PRs for versions older than v6 (with exceptions for critical security issues)

The file you modified is generated from the source code of [Sequelize 5](https://github.com/sequelize/sequelize/tree/v5), it has been committed here as an archive - we don't expect it to change anymore.

I invite you to migrate to Sequelize 6 instead, the breaking change list is not very long: https://sequelize.org/docs/v6/other-topics/upgrade/

**Comment by ephys** [comment]
Of course :)

It's automatically generated from the JSDoc in the sequelize repo: https://github.com/sequelize/website/blob/main/sync-repositories.sh#L41-L47

I recommend cloning the v6 branch of this repository: https://github.com/sequelize/sequelize/tree/v6

Then apply your changes in, I think, this folder: https://github.com/sequelize/sequelize/tree/v6/src/associations (don't forget to update the jsdoc in both .d.ts & .js)

You can then test your changes locally using:

```sh
yarn # Install branch deps & build
yarn docs # Generate v6 typedocs (it's a static website)
```

When ready, open a PR against the v6 branch. Once merged the website will be rebuilt to include the changes! :)

**Comment by ajatdarojat45** [comment]
Thank you @ephys, i have added my changes into this repo:  https://github.com/sequelize/sequelize/tree/v6
You can review my changes in this PR: https://github.com/sequelize/sequelize/pull/15065
Let me know if you have any questions.

**Comment by WikiRik** [comment]
Since we have moved to a different PR, I will close this one

**Pull request closed without merging**
