### PR TITLE
feat: add CTAs on homepage

### PR DESCRIPTION
**Pull request by ephys**
This PR adds links to the relevant documentation pages to the different steps of the homepage

image

And adds a CTA near the end of the page

image

I'm not super happy with how that secondary looks, advice welcome

### CODE REVIEW

**Comment by ephys** [comment]
The styling :)

**Comment by ephys** [comment]
How weird. That's what you get for testing on one browser only. It works pretty well on firefox mobile :x

I'll look into it

**Comment by WikiRik** [comment]
Just checked it out, I can also reproduce it using the Chrome DevTools

**Comment by ephys** [comment]
the culprit is this line:

```
@media (width < 800px)
```

I used the new range syntax but it's only supported in firefox and we don't have postcss installed to rewrite it

**Comment by sdepold** [comment]
Oh interesting. I think I tested it in many different variations but not thoroughly enough it seems :)

**Review by sdepold — APPROVED** [review]

**Pull request merged**
