### PR TITLE
Fix: incorrect lazy loading example in association docs

### PR DESCRIPTION
**Pull request by th3h4dyy**
In the `Providing the foreign key name directly` section in `Associations` docs, there's a **wrong** example which 
demonstrate the `lazy loading` when dealing with associations:

```js
const ship = Ship.findOne();
console.log((await ship.getCaptain()).toJSON());
```

**This will give us an error that says:**
`ship.getCaptain is not a function` since we cannot invoke the `getCaptain` yet.

This is wrong, because we're basically `await`ing on the `getCaptain()` result and not the `ship` itself which must be `await`ed first before the `getCaptain` instance method.

so, we can basically do something from the next solutions:
## Solution 1: 
```js
const ship = await Ship.findOne();
console.log((await ship.getCaptain()).toJSON());
```

## Solution 2: 
```js
const ship = Ship.findOne();
console.log((await (await ship).getCaptain()).toJSON());
```

### CODE REVIEW

**Review by ephys — APPROVED** [review]
Definitely prefer option 1, thank you :)

Edit: note that the same issue is present in the rest of the file
Would you also mind updating https://github.com/sequelize/website/blob/main/docs/core-concepts/assocs.md so the changes aren't lost in v7?

**Comment by th3h4dyy** [comment]
> Definitely prefer option 1, thank you :)
> 
> Edit: note that the same issue is present in the rest of the file Would you also mind updating https://github.com/sequelize/website/blob/main/docs/core-concepts/assocs.md so the changes aren't lost in v7?

yeah, sure, I'll update it directly

**Review by WikiRik — DISMISSED** [review]
Don't forget to update https://github.com/sequelize/website/blob/main/docs/core-concepts/assocs.md

**Comment by th3h4dyy** [comment]
> Don't forget to update https://github.com/sequelize/website/blob/main/docs/core-concepts/assocs.md

I think I've updated the rest of it.

**Comment by WikiRik** [comment]
You have updated the v6 version of the docs, but not the v7 version. It's two different files in the same branch. Please update the other file as well

**Comment by th3h4dyy** [comment]
> You have updated the v6 version of the docs, but not the v7 version. It's two different files in the same branch. Please update the other file as well

Oh, okay, thanks for letting me know this

**Review by ephys — APPROVED** [review]
I'll merge this without the v7 update because we're rewriting the v7 docs

**Pull request merged**
