### PR TITLE
Publish draft version on non-master branches

### PR DESCRIPTION
**Pull request by sdepold**
Commits on non-main branches will create draft versions of the documentation. I think we can remove the ci.yml if this works for everybody.

### CODE REVIEW

**Comment by ephys** [comment]
Can this be restricted to pushes on the main branch & to pull requests?

**Comment by sdepold** [comment]
@ephys i guess you want to cater for situations where we have commits without prs?

**Comment by ephys** [comment]
Yes, for WIP PRs. It would reduce the usage of our action minutes :)

**Comment by ephys** [comment]
How long do these stay alive? Do we need to call netlify to clean them up on PR close/merge?

**Comment by sdepold** [comment]
Good question. If I get this right, drafts are permanent:

https://answers.netlify.com/t/lifetime-of-draft-urls/6747

**Comment by sdepold** [comment]
Does not trigger for non-PR commits anymore:
https://github.com/sequelize/website/tree/blabb --> no action triggered

**Comment by sdepold** [comment]
After PR creation https://github.com/sequelize/website/actions/runs/2094403637

**Comment by sdepold** [comment]
@ephys I think this is ready

**Comment by ephys** [comment]
The one that was generated for https://github.com/sequelize/website/pull/67 doesn't include the changes from that PR, is that normal? :o

**Comment by sdepold** [comment]
> The preview generated for https://github.com/sequelize/website/pull/67 doesn't include the changes from that PR, is that normal? :o

I don't understand why it even commented 🤔 the draft creation is not on main yet?!

**Comment by sdepold** [comment]
Having said that, I did observe that sometime the comment would not end up on my pr. Maybe the or detection script doesn't work reliably

**Comment by ephys** [comment]
I think the get-pr-number script has an issue.
But iirc the "pull_request" event gives it, let me find the relevant documentation

**Comment by sdepold** [comment]
> I think the get-pr-number script has an issue. But iirc the "pull_request" event gives it, let me find the relevant documentation

I believe I read something about that in the script's description. I was a bit worries about it when I made the PR scope change :)

**Comment by ephys** [comment]
I think it's `github.event.pull_request.number`

**Comment by sdepold** [comment]
@ephys sweet! works

**Review by ephys — APPROVED** [review]

**Pull request merged**
