### PR TITLE
feat(homepage): add /v6 redirects

### PR DESCRIPTION
**Pull request by sdepold**

### CODE REVIEW

**Comment by ephys** [comment]
Because we've had issues with this in the past, I'll run a script to list the existing /v6 pages then see if anything results in a 404 on the new site

**Comment by sdepold** [comment]
fwiw: The redirect rules are doing exactly that. They follow all existing links that are generated by the documentation and add an alias to the right url

**Comment by ephys** [comment]
I've added filters to `ephys/puppeteer-crawler`. Here are all URLs that are under `/v6`:

```
"https://sequelize.org/",
"https://sequelize.org/v6",
"https://sequelize.org/v6/",
"https://sequelize.org/v6/identifiers.html",
"https://sequelize.org/v6/index.html",
"https://sequelize.org/v6/manual/getting-started.html",
"https://sequelize.org/v6/manual/model-basics.html",
"https://sequelize.org/v6/manual/model-instances.html",
"https://sequelize.org/v6/manual/model-querying-basics.html",
"https://sequelize.org/v6/manual/model-querying-finders.html",
"https://sequelize.org/v6/manual/getters-setters-virtuals.html",
"https://sequelize.org/v6/manual/validations-and-constraints.html",
"https://sequelize.org/v6/manual/raw-queries.html",
"https://sequelize.org/v6/manual/assocs.html",
"https://sequelize.org/v6/manual/paranoid.html",
"https://sequelize.org/v6/manual/eager-loading.html",
"https://sequelize.org/v6/manual/creating-with-associations.html",
"https://sequelize.org/v6/manual/advanced-many-to-many.html",
"https://sequelize.org/v6/manual/association-scopes.html",
"https://sequelize.org/v6/manual/polymorphic-associations.html",
"https://sequelize.org/v6/manual/dialect-specific-things.html",
"https://sequelize.org/v6/manual/transactions.html",
"https://sequelize.org/v6/manual/hooks.html",
"https://sequelize.org/v6/manual/query-interface.html",
"https://sequelize.org/v6/manual/naming-strategies.html",
"https://sequelize.org/v6/manual/scopes.html",
"https://sequelize.org/v6/manual/sub-queries.html",
"https://sequelize.org/v6/manual/other-data-types.html",
"https://sequelize.org/v6/manual/constraints-and-circularities.html",
"https://sequelize.org/v6/manual/extending-data-types.html",
"https://sequelize.org/v6/manual/indexes.html",
"https://sequelize.org/v6/manual/optimistic-locking.html",
"https://sequelize.org/v6/manual/read-replication.html",
"https://sequelize.org/v6/manual/connection-pool.html",
"https://sequelize.org/v6/manual/legacy.html",
"https://sequelize.org/v6/manual/migrations.html",
"https://sequelize.org/v6/manual/typescript.html",
"https://sequelize.org/v6/manual/resources.html",
"https://sequelize.org/v6/manual/upgrade-to-v6.html",
"https://sequelize.org/v6/manual/whos-using.html",
"https://sequelize.org/v6/manual/aws-lambda.html",
"https://sequelize.org/v6/manual/legal.html",
"https://sequelize.org/v6/class/src/sequelize.js~Sequelize.html",
"https://sequelize.org/v6/class/src/model.js~Model.html",
"https://sequelize.org/v6/variable/index.html",
"https://sequelize.org/v6/manual/data-types.html",
"https://sequelize.org/v6/class/src/dialects/abstract/query-interface.js~QueryInterface.html",
"https://sequelize.org/v6/manual/models-definition.html",
"https://sequelize.org/v6/manual/associations.html",
"https://sequelize.org/v6/manual/models-usage.html",
"https://sequelize.org/v6/manual/querying.html",
"https://sequelize.org/v6/class/src/transaction.js~Transaction.html",
"https://sequelize.org/v6/function/index.html",
"https://sequelize.org/v6/class/src/associations/base.js~Association.html",
"https://sequelize.org/v6/class/src/associations/belongs-to-many.js~BelongsToMany.html",
"https://sequelize.org/v6/class/src/associations/belongs-to.js~BelongsTo.html",
"https://sequelize.org/v6/class/src/associations/has-many.js~HasMany.html",
"https://sequelize.org/v6/class/src/associations/has-one.js~HasOne.html",
"https://sequelize.org/v6/class/src/dialects/db2/query-interface.js~Db2QueryInterface.html",
"https://sequelize.org/v6/class/src/dialects/mssql/async-queue.ts~AsyncQueueError.html",
"https://sequelize.org/v6/class/src/dialects/mssql/query-interface.js~MSSqlQueryInterface.html",
"https://sequelize.org/v6/class/src/dialects/mysql/query-interface.js~MySQLQueryInterface.html",
"https://sequelize.org/v6/class/src/dialects/postgres/query-interface.js~PostgresQueryInterface.html",
"https://sequelize.org/v6/class/src/dialects/snowflake/query-interface.js~SnowflakeQueryInterface.html",
"https://sequelize.org/v6/class/src/dialects/sqlite/query-interface.js~SQLiteQueryInterface.html",
"https://sequelize.org/v6/class/src/errors/aggregate-error.ts~AggregateError.html",
"https://sequelize.org/v6/class/src/errors/association-error.ts~AssociationError.html",
"https://sequelize.org/v6/class/src/errors/base-error.ts~BaseError.html",
"https://sequelize.org/v6/class/src/errors/bulk-record-error.ts~BulkRecordError.html",
"https://sequelize.org/v6/class/src/errors/connection-error.ts~ConnectionError.html",
"https://sequelize.org/v6/class/src/errors/database-error.ts~DatabaseError.html",
"https://sequelize.org/v6/class/src/errors/eager-loading-error.ts~EagerLoadingError.html",
"https://sequelize.org/v6/class/src/errors/empty-result-error.ts~EmptyResultError.html",
"https://sequelize.org/v6/class/src/errors/instance-error.ts~InstanceError.html",
"https://sequelize.org/v6/class/src/errors/optimistic-lock-error.ts~OptimisticLockError.html",
"https://sequelize.org/v6/class/src/errors/query-error.ts~QueryError.html",
"https://sequelize.org/v6/class/src/errors/sequelize-scope-error.ts~SequelizeScopeError.html",
"https://sequelize.org/v6/class/src/errors/validation-error.ts~ValidationError.html",
"https://sequelize.org/v6/class/src/errors/validation-error.ts~ValidationErrorItem.html",
"https://sequelize.org/v6/class/src/errors/connection/access-denied-error.ts~AccessDeniedError.html",
"https://sequelize.org/v6/class/src/errors/connection/connection-acquire-timeout-error.ts~ConnectionAcquireTimeoutError.html",
"https://sequelize.org/v6/class/src/errors/connection/connection-refused-error.ts~ConnectionRefusedError.html",
"https://sequelize.org/v6/class/src/errors/connection/connection-timed-out-error.ts~ConnectionTimedOutError.html",
"https://sequelize.org/v6/class/src/errors/connection/host-not-found-error.ts~HostNotFoundError.html",
"https://sequelize.org/v6/class/src/errors/connection/host-not-reachable-error.ts~HostNotReachableError.html",
"https://sequelize.org/v6/class/src/errors/connection/invalid-connection-error.ts~InvalidConnectionError.html",
"https://sequelize.org/v6/class/src/errors/database/exclusion-constraint-error.ts~ExclusionConstraintError.html",
"https://sequelize.org/v6/class/src/errors/database/foreign-key-constraint-error.ts~ForeignKeyConstraintError.html",
"https://sequelize.org/v6/class/src/errors/database/timeout-error.ts~TimeoutError.html",
"https://sequelize.org/v6/class/src/errors/database/unknown-constraint-error.ts~UnknownConstraintError.html",
"https://sequelize.org/v6/class/src/errors/validation/unique-constraint-error.ts~UniqueConstraintError.html",
"https://sequelize.org/v6/class/src/data-types.js~ARRAY.html",
"https://sequelize.org/v6/class/src/data-types.js~VIRTUAL.html",
"https://sequelize.org/v6/class/src/data-types.js~UUIDV4.html",
"https://sequelize.org/v6/class/src/data-types.js~UUIDV1.html",
"https://sequelize.org/v6/class/src/data-types.js~UUID.html",
"https://sequelize.org/v6/class/src/data-types.js~TSVECTOR.html",
"https://sequelize.org/v6/class/src/data-types.js~TINYINT.html",
"https://sequelize.org/v6/class/src/data-types.js~TIME.html",
"https://sequelize.org/v6/class/src/data-types.js~TEXT.html",
"https://sequelize.org/v6/class/src/data-types.js~STRING.html",
"https://sequelize.org/v6/class/src/data-types.js~SMALLINT.html",
"https://sequelize.org/v6/class/src/data-types.js~REAL.html",
"https://sequelize.org/v6/class/src/data-types.js~RANGE.html",
"https://sequelize.org/v6/class/src/data-types.js~NUMBER.html",
"https://sequelize.org/v6/class/src/data-types.js~NOW.html",
"https://sequelize.org/v6/class/src/data-types.js~MEDIUMINT.html",
"https://sequelize.org/v6/class/src/data-types.js~MACADDR.html",
"https://sequelize.org/v6/class/src/data-types.js~JSONTYPE.html",
"https://sequelize.org/v6/class/src/data-types.js~JSONB.html",
"https://sequelize.org/v6/class/src/data-types.js~INTEGER.html",
"https://sequelize.org/v6/class/src/data-types.js~INET.html",
"https://sequelize.org/v6/class/src/data-types.js~HSTORE.html",
"https://sequelize.org/v6/class/src/data-types.js~GEOMETRY.html",
"https://sequelize.org/v6/class/src/data-types.js~GEOGRAPHY.html",
"https://sequelize.org/v6/class/src/data-types.js~FLOAT.html",
"https://sequelize.org/v6/class/src/data-types.js~ENUM.html",
"https://sequelize.org/v6/class/src/data-types.js~DOUBLE.html",
"https://sequelize.org/v6/class/src/data-types.js~DECIMAL.html",
"https://sequelize.org/v6/class/src/data-types.js~DATEONLY.html",
"https://sequelize.org/v6/class/src/data-types.js~DATE.html",
"https://sequelize.org/v6/class/src/data-types.js~CITEXT.html",
"https://sequelize.org/v6/class/src/data-types.js~CIDR.html",
"https://sequelize.org/v6/class/src/data-types.js~CHAR.html",
"https://sequelize.org/v6/class/src/data-types.js~BOOLEAN.html",
"https://sequelize.org/v6/class/src/data-types.js~BLOB.html",
"https://sequelize.org/v6/class/src/data-types.js~BIGINT.html"
```

**Comment by ephys** [comment]
PS: I think it's fine if we don't redirect the API references as long as we make sure google unlists these URLs

**Comment by ephys** [comment]
I still don't see how to fix this issue with the limitations of docusaurus. And, unfortunately, github pages still doesn't provide a simple way to add redirections.

Should we try hosting on netlify instead? https://docs.netlify.com/routing/redirects/
I think we may be eligible for their open source program https://www.netlify.com/legal/open-source-policy

**Pull request closed without merging**
