### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by sdepold**
Bildschirmfoto 2022-03-18 an 20 02 07

### CODE REVIEW

**Comment by ephys** [comment]
I'm doing a few modifications, I'll try to list them all here:

support for dark mode & intermediary screen size support
image

Fixing contrast issues
image

white logos for contrast
image

**Comment by sdepold** [comment]
Oooh i love the idea with the logos

**Comment by ephys** [comment]
I changed the primary color of the dark theme to improve its contrast with a dark background:
image. It's `#02afef` (the background color of the first colorful section)

**Comment by ephys** [comment]
I've completed the changes :) 
I tried to not modify the essence of your design. I only touched color contrast issues (I aimed for AA), fixed a few responsive issues (the site look great no matter the screen size now), and added support for the dark theme

**Comment by sdepold** [comment]
👌👌👌👌👌

**Pull request merged**
