### PR TITLE
Netlify-based redirect rules

### PR DESCRIPTION
**Pull request by sdepold**
Supersedes #16. Can be tested here: https://capable-youtiao-134aad.netlify.app/

The problem is however, that the urls don't match:

- https://sequelize.org/v6/manual/dialect-specific-things.html --> https://capable-youtiao-134aad.netlify.app/docs/v6/other-topics/dialect-specific-things

I guess we could somehow walk through the file system and generate the redirects file automatically but is that worth it and do we really care enough to try?

Please note that the PR is currently only half working. `/manual` should be replaced with something else (as indicated above).

### CODE REVIEW

**Comment by sdepold** [comment]
A push to this PR / branch should theoretically deploy the netlify page

**Comment by ephys** [comment]
> do we really care enough to try?

It's pretty important as current search results will break if we don't
Shouldn't take too long, I already have both lists, I can look into it

**Comment by WikiRik** [comment]
Not sure if this is the best issue/PR to mention this but do we really need Netlify? Does GitHub Pages not satisfy our needs?

**Comment by ephys** [comment]
The reason behind the host change is that github doesn't provide a way to set redirection rules. We tried doing them on the front-end instead but docusaurus's plugin doesn't support redirecting from .html extensions.

(https://github.com/sequelize/website/pull/16#issuecomment-1075216718)

Netlify has an open source plan so it should be free for us maybe hopefully. The PR preview is also a nice bonus

**Comment by ephys** [comment]
Proposition for the redirection file:

```
/main/* /v6/:splat 302
/master/* /v6/:splat 302

/v6 /docs/v6/intro 302
/v6/manual/advanced-many-to-many.html			/docs/v6/advanced-association-concepts/advanced-many-to-many 302
/v6/manual/association-scopes.html				/docs/v6/advanced-association-concepts/association-scopes 302
/v6/manual/creating-with-associations.html		/docs/v6/advanced-association-concepts/creating-with-associations 302
/v6/manual/eager-loading.html					/docs/v6/advanced-association-concepts/eager-loading 302
/v6/manual/polymorphic-associations.html		/docs/v6/advanced-association-concepts/polymorphic-associations 302
/v6/manual/advanced-association-concepts.html	/docs/v6/category/advanced-association-concepts 302
/v6/manual/core-concepts.html					/docs/v6/category/core-concepts 302
/v6/manual/other-topics.html					/docs/v6/category/other-topics 302
/v6/manual/assocs.html							/docs/v6/core-concepts/assocs 302
/v6/manual/getters-setters-virtuals.html		/docs/v6/core-concepts/getters-setters-virtuals 302
/v6/manual/model-basics.html					/docs/v6/core-concepts/model-basics 302
/v6/manual/model-instances.html					/docs/v6/core-concepts/model-instances 302
/v6/manual/model-querying-basics.html			/docs/v6/core-concepts/model-querying-basics 302
/v6/manual/model-querying-finders.html			/docs/v6/core-concepts/model-querying-finders 302
/v6/manual/paranoid.html						/docs/v6/core-concepts/paranoid 302
/v6/manual/raw-queries.html						/docs/v6/core-concepts/raw-queries 302
/v6/manual/validations-and-constraints.html		/docs/v6/core-concepts/validations-and-constraints 302
/v6/manual/associations.html					/docs/v6/moved/associations 302
/v6/manual/data-types.html						/docs/v6/moved/data-types 302
/v6/manual/models-definition.html				/docs/v6/moved/models-definition 302
/v6/manual/models-usage.html					/docs/v6/moved/models-usage 302
/v6/manual/querying.html						/docs/v6/moved/querying 302
/v6/manual/aws-lambda.html						/docs/v6/other-topics/aws-lambda 302
/v6/manual/connection-pool.html					/docs/v6/other-topics/connection-pool 302
/v6/manual/constraints-and-circularities.html	/docs/v6/other-topics/constraints-and-circularities 302
/v6/manual/dialect-specific-things.html			/docs/v6/other-topics/dialect-specific-things 302
/v6/manual/extending-data-types.html			/docs/v6/other-topics/extending-data-types 302
/v6/manual/hooks.html							/docs/v6/other-topics/hooks 302
/v6/manual/indexes.html							/docs/v6/other-topics/indexes 302
/v6/manual/legacy.html							/docs/v6/other-topics/legacy 302
/v6/manual/legal.html							/docs/v6/other-topics/legal 302
/v6/manual/migrations.html						/docs/v6/other-topics/migrations 302
/v6/manual/naming-strategies.html				/docs/v6/other-topics/naming-strategies 302
/v6/manual/optimistic-locking.html				/docs/v6/other-topics/optimistic-locking 302
/v6/manual/other-data-types.html				/docs/v6/other-topics/other-data-types 302
/v6/manual/query-interface.html					/docs/v6/other-topics/query-interface 302
/v6/manual/read-replication.html				/docs/v6/other-topics/read-replication 302
/v6/manual/resources.html						/docs/v6/other-topics/resources 302
/v6/manual/scopes.html							/docs/v6/other-topics/scopes 302
/v6/manual/sub-queries.html						/docs/v6/other-topics/sub-queries 302
/v6/manual/transactions.html					/docs/v6/other-topics/transactions 302
/v6/manual/typescript.html						/docs/v6/other-topics/typescript 302
/v6/manual/upgrade-to-v6.html					/docs/v6/other-topics/upgrade-to-v6 302
```

**Comment by sdepold** [comment]
I just updated the file which should eventually lead to a deployment of the website. Do I understand it right, that we are catering for a https://sequelize.org/main/manual/dialect-specific-things.html

via 

https://sequelize.org/main/manual/dialect-specific-things.html
--> https://sequelize.org/v6/manual/dialect-specific-things.html
--> https://sequelize.org/docs/v6/other-topics/dialect-specific-things

So a 3 step redirect?

**Comment by sdepold** [comment]
Also, once this is proven to work, I would 

a) swap the 302 to 301
b) replace the gh-pages branch update with a direct upload to netlify using their CLI

**Comment by ephys** [comment]
> So a 3 step redirect?

Yup!
It's going to be slightly slower but it's not going to matter much once browsers/search engines update their redirection cache

Actually right now it's 3 redirections:

[sequelize.org/main/manual/dialect-specific-things.html](https://sequelize.org/main/manual/dialect-specific-things.html)
--> [sequelize.org/v6/manual/dialect-specific-things.html](https://sequelize.org/v6/manual/dialect-specific-things.html)
--> [sequelize.org/docs/v6/other-topics/dialect-specific-things](https://sequelize.org/docs/v6/other-topics/dialect-specific-things)
--> [sequelize.org/docs/v6/other-topics/dialect-specific-things/](https://sequelize.org/docs/v6/other-topics/dialect-specific-things/)

Because we have trailing slashes enabled. We should either disable trailing slashes or add them to our redirection file.

Just tested (not everything, just this URL) and it looks good through

https://capable-youtiao-134aad.netlify.app/main/manual/dialect-specific-things.html

**Comment by sdepold** [comment]
super nice :) I'm fine with trailing slash or without :D I don't really care

**Comment by ephys** [comment]
If the site is fully static, it's probably [netlify](https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash) that is adding the trailing slash

**Comment by sdepold** [comment]
https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash

**Comment by sdepold** [comment]
ah you have found it already. :D

**Comment by WikiRik** [comment]
> The reason behind the host change is that github doesn't provide a way to set redirection rules. We tried doing them on the front-end instead but docusaurus's plugin doesn't support redirecting from .html extensions.

Ah, I missed that comment. Thanks!

**Comment by sdepold** [comment]
I just added trailing slashes to the Docusaurus config

**Comment by sdepold** [comment]
As discussed on slack, I'm
Merging this now and we'll do a final review once everything is complete

**Pull request merged**
